[toolchain]
package_manager = "Yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
solana_hello_world = "2LQ8fWSFrQJ7e8WcomnbhLFjayNRbTMQLZNzEqRKmaJ3"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
